fix: do not use cargo --locked in library release workflow
Since libraries should not have a lockfile committed[^1], this will cause
errors like:

```
error: the lock file /Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

[^1]: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html